export const products = [
    {
        name: "Don Valentin",
        cellar: "Bianchi",
        price: 500,
        description: "La evolución del gran clásico de la viticultura argentina se expresa en esta línea de varietales jóvenes que incorpora las mejores expresiones de cada cepa. En Bodega Bianchi el legado de saber hacer vino y la pasión por la calidad de nuestro fundador trasmitida de generación en generación se refleja en cada botella",
        image: "https://cdn.shopify.com/s/files/1/0005/4634/0925/products/DVLDescorchados-2._2048x2048.png?v=1586964033",
    },
    {
        name: "Viamonte Reserva",
        cellar: "Viamonte",
        price: 600,
        description: "Se perciben intensos aromas a frutos rojos y negros maduros como moras y casis, con una nota de vainilla que otorga elegancia",
        image: "https://viamontewinery.com/wp-content/uploads/2018/11/viamonte-suelos-cabernet.jpg",
    },
    {
        name: "Don Valentin",
        cellar: "Bianchi",
        price: 500,
        description: "La evolución del gran clásico de la viticultura argentina se expresa en esta línea de varietales jóvenes que incorpora las mejores expresiones de cada cepa. En Bodega Bianchi el legado de saber hacer vino y la pasión por la calidad de nuestro fundador trasmitida de generación en generación se refleja en cada botella",
        image: "https://cdn.shopify.com/s/files/1/0005/4634/0925/products/DVLDescorchados-2._2048x2048.png?v=1586964033",
    },
    {
        name: "Viamonte Reserva",
        cellar: "Viamonte",
        price: 600,
        description: "Se perciben intensos aromas a frutos rojos y negros maduros como moras y casis, con una nota de vainilla que otorga elegancia",
        image: "https://viamontewinery.com/wp-content/uploads/2018/11/viamonte-suelos-cabernet.jpg",
    },
    {
        name: "Don Valentin",
        cellar: "Bianchi",
        price: 500,
        description: "La evolución del gran clásico de la viticultura argentina se expresa en esta línea de varietales jóvenes que incorpora las mejores expresiones de cada cepa. En Bodega Bianchi el legado de saber hacer vino y la pasión por la calidad de nuestro fundador trasmitida de generación en generación se refleja en cada botella",
        image: "https://cdn.shopify.com/s/files/1/0005/4634/0925/products/DVLDescorchados-2._2048x2048.png?v=1586964033",
    },
    {
        name: "Viamonte Reserva",
        cellar: "Viamonte",
        price: 600,
        description: "Se perciben intensos aromas a frutos rojos y negros maduros como moras y casis, con una nota de vainilla que otorga elegancia",
        image: "https://viamontewinery.com/wp-content/uploads/2018/11/viamonte-suelos-cabernet.jpg",
    },
    {
        name: "Don Valentin",
        cellar: "Bianchi",
        price: 500,
        description: "La evolución del gran clásico de la viticultura argentina se expresa en esta línea de varietales jóvenes que incorpora las mejores expresiones de cada cepa. En Bodega Bianchi el legado de saber hacer vino y la pasión por la calidad de nuestro fundador trasmitida de generación en generación se refleja en cada botella",
        image: "https://cdn.shopify.com/s/files/1/0005/4634/0925/products/DVLDescorchados-2._2048x2048.png?v=1586964033",
    },
    {
        name: "Viamonte Reserva",
        cellar: "Viamonte",
        price: 600,
        description: "Se perciben intensos aromas a frutos rojos y negros maduros como moras y casis, con una nota de vainilla que otorga elegancia",
        image: "https://viamontewinery.com/wp-content/uploads/2018/11/viamonte-suelos-cabernet.jpg",
    },
    {
        name: "Don Valentin",
        cellar: "Bianchi",
        price: 500,
        description: "La evolución del gran clásico de la viticultura argentina se expresa en esta línea de varietales jóvenes que incorpora las mejores expresiones de cada cepa. En Bodega Bianchi el legado de saber hacer vino y la pasión por la calidad de nuestro fundador trasmitida de generación en generación se refleja en cada botella",
        image: "https://cdn.shopify.com/s/files/1/0005/4634/0925/products/DVLDescorchados-2._2048x2048.png?v=1586964033",
    },
    {
        name: "Viamonte Reserva",
        cellar: "Viamonte",
        price: 600,
        description: "Se perciben intensos aromas a frutos rojos y negros maduros como moras y casis, con una nota de vainilla que otorga elegancia",
        image: "https://viamontewinery.com/wp-content/uploads/2018/11/viamonte-suelos-cabernet.jpg",
    },
    {
        name: "Don Valentin",
        cellar: "Bianchi",
        price: 500,
        description: "La evolución del gran clásico de la viticultura argentina se expresa en esta línea de varietales jóvenes que incorpora las mejores expresiones de cada cepa. En Bodega Bianchi el legado de saber hacer vino y la pasión por la calidad de nuestro fundador trasmitida de generación en generación se refleja en cada botella",
        image: "https://cdn.shopify.com/s/files/1/0005/4634/0925/products/DVLDescorchados-2._2048x2048.png?v=1586964033",
    },
    {
        name: "Viamonte Reserva",
        cellar: "Viamonte",
        price: 600,
        description: "Se perciben intensos aromas a frutos rojos y negros maduros como moras y casis, con una nota de vainilla que otorga elegancia",
        image: "https://viamontewinery.com/wp-content/uploads/2018/11/viamonte-suelos-cabernet.jpg",
    },
];