TRUNCATE TABLE products;

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Alma Mora','Tinto','Finca Las Moras',605,'De color rojo rubí. Sabor a frutas negras, pimiento rojo, vainilla y chocolate. De textura suave y sabor duradero.','https://hiperlibertad.vteximg.com.br/arquivos/ids/161524-600-600/Vino-Tinto-Malbec-Alma-Mora-Reserva-750-cc-1-4478.jpg?v=637287212383600000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Don Valentin','Tinto','Bianchi',500,'La evolución del gran clásico de la viticultura argentina se expresa en esta línea de varietales jóvenes que incorpora las mejores expresiones de cada cepa. En Bodega Bianchi el legado de saber hacer vino y la pasión por la calidad de nuestro fundador trasmitida de generación en generación se refleja en cada botella','https://hiperlibertad.vteximg.com.br/arquivos/ids/162194-600-600/Vino-Tinto-Don-Valent-n-Lacrado-750-cc-1-6646.jpg?v=637287215402130000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Viamonte Reserva','Tinto','Viamonte',600,'Se perciben intensos aromas a frutos rojos y negros maduros como moras y casis, con una nota de vainilla que otorga elegancia','https://viamontewinery.com/wp-content/uploads/2018/11/viamonte-suelos-cabernet.jpg' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Fabre Montmayou','Tinto','Fabre Montmayou',1930,'Color rojo intenso con tonos violetas. Aromas intensos de cerezas rojas y especias. Complejo y equilibrado con notas de vainilla y de chocolate proveniente de la crianza en barrica. Un vino moderno, con taninos suaves y sedosos. Perfecto con todo tipo de carnes a la parrilla, caza y quesos','https://hiperlibertad.vteximg.com.br/arquivos/ids/189720-600-600/VINO-FABRE-TERRU-O-CABERNET-SAUVIGNON-X-750-Ml-1-24563.jpg?v=637764969761000000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Los Haroldos','Tinto','Finca Las Moras',1240,'Las uvas Cabernet Sauvignon provenientes de una cuidadosa selección de parcelas, con muy bajo rendimiento de racimos por planta, logran un vino de color rojizo profundo con matices negros. Su innovador proceso de elaboración, que contempla una maduración del vino en barricas de roble Bourbon, aporta notas a humo, caramelo y miel. En boca, el tostado medio, aporta sabores a chocolate y pimientos asados. Final dulce, complejo y largo.','https://hiperlibertad.vteximg.com.br/arquivos/ids/191776-600-600/VINO-LOS-HAROLDOS-GRAN-CORTE-X-750-Ml-1-15151.jpg?v=637796073877700000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Chacabuco','Tinto','El Esteco',510,'Más allá de su esperada intensidad cromática, sus lágrimas coloreadas y espesas formadas en la copa anuncian una muy interesante estructura y madurez. Aroma: Su concentrado perfil aromático se centra en frutos rojos bien maduros. Muestra, además, notas de pasas de uva y leves hierbas frescas, combinadas con finas notas de roble y café, aportado por su añejamiento en barricas. Sabor: Presenta taninos maduros y vibrantes en boca que, junto con una sensación de frutas negras, llevan a un prolongado y elegante final','https://hiperlibertad.vteximg.com.br/arquivos/ids/172352-600-600/VINO-CHACABUCO-MALBEC-1500-CC-1-12645.jpg?v=637461714268730000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Fond de Cave','Tinto','Trapiche',560,'De color rojo púrpura con reflejos violáceos, este vino entrega aromas de mermelada de casis y ciruela con un sutil fondo de vainilla. Su entrada es voluminosa con taninos dulces, con persistentes notas de vainilla','https://hiperlibertad.vteximg.com.br/arquivos/ids/161599-600-600/Vino-Tinto-Malbec-Fond-de-Cave-750-cc-1-8408.jpg?v=637287212603700000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('El Que Rie Último Rie Mejor','Tinto','San Telmo',740,'Aromas a frutas rojas confitadas que luego dan paso a notas como frutos secos, vainilla y leve nota especiada','https://hiperlibertad.vteximg.com.br/arquivos/ids/179341-600-600/VINO-EL-QUE-RIE-ULTIMO-750ML-1-19005.jpg?v=637568918395930000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Finca Natalina','Tinto','El Esteco',515,'Color: Bordó profundo con fondo negro e intenso y reflejos violáceos en sus bordes. Limpio, brillante y muy denso. Joven. Lágrimas muy coloreadas y densas. Aroma: concentrados e intensos. Aromas a frutos bien maduros. Frutado, chocolate negro y delicadas notas de café y roble, aportado por su añejamiento en barricas. Sabor: entrada con mucho volumen, con taninos dulces, maduros, frescos y final tiza. Armónico con percepción frutal. Vino concentrado, de persistencia larga y elegante','https://hiperlibertad.vteximg.com.br/arquivos/ids/179465-600-600/VINO-FINCA-NATALINA-BLACK-BLEND-750ML-1-18760.jpg?v=637569704397200000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Casillero del Diablo','Tinto','Navarro Correas',950,'Color rojo oscuro, brillante y profundo. Aromas y sabores a ciruelas, membrillo, moras, trufas y grafito. Vino de gran complejidad aromática y taninos redondos, dulces, que aportan una textura sedosa dando un buen relieve en boca. Gran equilibrio entre alcohol, acidez y fruta. De final prolongado','https://hiperlibertad.vteximg.com.br/arquivos/ids/184679-600-600/VINO-CASILLERO-DEL-DIABLO-RED-BLEND-750ML-1-22851.jpg?v=637641621777500000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Trivento','Tinto','Navarro Correas',2000,'De color rojo intenso, aromas y sabores a violetas, ciruelas, cerezas, frutos rojos y pimienta negra. Taninos firmes y redondos, cuerpo medio alto, muy frutado con gran equilibrio entre alcohol y frescura','https://hiperlibertad.vteximg.com.br/arquivos/ids/188957-600-600/VINO-TRIVENTO-GOLDEN-RESERVE-CABERNET-SAUVIGNON-X-750-Ml-1-22749.jpg?v=637757841973630000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Canciller','Tinto','Mascota Vineyards',490,'De color rojo cereza intenso; Unánime se destaca por su marcado sabor a fruta y complejidad aromática. Su paso de 20 meses en barricas de roble francés le otorga aroma a chocolate y tabaco; con un toque de pimienta negra. Posee buena estructura y taninos redondos que se complementan perfectamente con su acidez fresca y jugosa','https://hiperlibertad.vteximg.com.br/arquivos/ids/190632-600-600/VINO-CANCILLER-MALBEC-X-1125-Ml-1-23876.jpg?v=637780521839770000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Coliman','Blanco','Finca Las Moras',235,'De color dorado con matices verdosos. De nariz fresca y frutal. Se destacan aromas a manzana verde y pera. En boca se aprecian delicadas notas a frutas de carozo, como el durazno maduro. Untuoso y refrescante','https://hiperlibertad.vteximg.com.br/arquivos/ids/174921-600-600/Vino-Blanco-Coliman-Cl-sico-750-mL-1-14362.jpg?v=637511867301570000' ,1);


INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Suter','Blanco','Elementos',255,'Vista:Amarillo suave brillante con leves notas verdosas. Aroma: Aromas elegantes con marcadas notas cítricas combinadas con leves con notas tropicales, cáscara de pomelo y ají amarillo. Sabor: Fruta madura que llena el paladar, levemente cremoso y con notas de espárrago y ají amarillo. Gran fineza y un final límpido','https://hiperlibertad.vteximg.com.br/arquivos/ids/183918-600-600/VINO-BLANCO-SUTER-ETIQUETA-MARR-N-X-750CC-1-21300.jpg?v=637626932770830000' ,1);


INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Bowen','Blanco','Costa & Pampa',273,'De un fino color amarillo con dejos verdosos, posee notas a hierbas frescas, intenso aroma a ruda y suaves notas cítricas. Presenta textura caudalosa en boca, fresco y con marcada presencia mineral','https://hiperlibertad.vteximg.com.br/arquivos/ids/182741-600-600/VINO-BLANCO-DULCE-BOWEN-X-750ML-1-20973.jpg?v=637608582089600000' ,1);


INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Norton Cosecha Tardía','Blanco','Norton',500,'De color amarillo verdoso claro con reflejos dorados. Su aroma recuerda al ananá y pomelo rosado y a las frutas de carozo','https://hiperlibertad.vteximg.com.br/arquivos/ids/191644-600-600/VINO-NORTON-COSECHA-TARD-A-X-375-Ml-1-25204.jpg?v=637794345854000000' ,1);


INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Estancia Mendoza','Blanco','Trapiche',340,'Este Chardonnay frutado ofrece aromas a frutas tropicales con sutiles notas especiadas. En boca es crujiente desplegando su cuerpo completo, sabores frutados y mineralidad. Presenta un final encantador y persistente','https://hiperlibertad.vteximg.com.br/arquivos/ids/191188-600-600/VINO-ESTANCIA-MENDOZA-CHARDONNAY-CHENIN-X-750-Ml-1-4773.jpg?v=637787433679570000' ,1);


INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Elementos','Blanco','Elementos',335,'Amarillo brillante, con tonalidades platinadas y sutiles tonos verdes. De aroma delicado pero a la vez intenso, con fuertes notas que recuerdan a las rosas y cócteles de fruta, combinados con aromas a cáscaras de naranjas y duraznos. Abundancia de sabores cítricos, fresco con un buen balance en boca, amable y agradable entrada dulce. Con buena acidez','https://hiperlibertad.vteximg.com.br/arquivos/ids/172249-600-600/VINO-ELEMENTOS-TORRENTES-X-750ML-1-12698.jpg?v=637461714041800000' ,1);


INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Alaris','Blanco','Trapiche',340,'De color amarillo verdoso. Sabor a frutas tropicales como ananá y bananas. Textura suave y final fresco','https://hiperlibertad.vteximg.com.br/arquivos/ids/163310-600-600/Vino-Blanco-Dulce-Trapiche-Alaris-750-cc-1-6084.jpg?v=637291517743500000' ,1);


INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Don Valentín','Blanco','Bianchi',370,'De color amarillo muy brillante con notas verdosas. notas de frutos tropicales y flores de naranjo, delicados cítricos, duraznos blancos, uva torrontés. muy delicado roble. persistente y refrescante. con buen cuerpo y una acidez integrada','https://hiperlibertad.vteximg.com.br/arquivos/ids/164366-600-600/Vino-Blanco-Don-Valentin-Lacrado-750-cc-1-8570.jpg?v=637293037135000000' ,1);





INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Finca Natalina','Blanco','El Esteco',450,'Complejo Chardonnay de color ámbar oscuro y carácter expresivo. Su cuidada elaboración, inspirada en los destilados más prestigiosos del mundo, contempla una maduración del vino en barricas de roble Bourbon que han aportado características particulares. En nariz se destacan aromas a ananá maduro combinadas con la vainilla, caramelo y notas ahumadas del contacto con barricas de Missouri. En boca es untuoso con un dulce y persistente final','https://hiperlibertad.vteximg.com.br/arquivos/ids/193133-600-600/VINO-FINCA-NATALINA-CHARDONNAY-X-750-Ml-1-9473.jpg?v=637814217705530000' ,1);


INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Chacabuco','Blanco','El Esteco',380,'De un fino color dorado y leves tonos verdosos, posee notas a manzanas verdes, pera y dejos de pan tostado y manteca. Se presenta fresco en boca con marcada presencia mineral y final largo y untuoso','https://hiperlibertad.vteximg.com.br/arquivos/ids/177234-600-600/VINO-CHACABUCO-VIOGNIER-750-CC-1-8686.jpg?v=637551487248730000' ,1);


INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Valmont','Blanco','Finca Las Moras',390,'De color dorado con matices verdosos. De nariz fresca y frutal. Se destacan aromas a manzana verde y pera. En boca se aprecian delicadas notas a frutas de carozo, como el durazno maduro. Untuoso y refrescante','https://hiperlibertad.vteximg.com.br/arquivos/ids/176654-600-600/Vino-Blanco-Valmont-750-mL-1-16547.jpg?v=637544532362400000' ,1);


INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Marcus','Blanco','Norton',410,'De color amarillo muy brillante con notas verdosas. notas de frutos tropicales y flores de naranjo, delicados cítricos, duraznos blancos, uva torrontés. muy delicado roble. persistente y refrescante. con buen cuerpo y una acidez integrada','https://hiperlibertad.vteximg.com.br/arquivos/ids/188919-600-600/VINO-MARCUS-SAUVIGNON-BLANC-X-750-Ml-1-14207.jpg?v=637757841875770000' ,1);


INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Elementos','Rosado','Elementos',570,'Posee un color rosa pálido. En nariz, presenta aroma a frutas rojas como cerezas y frambuesas, balanceado con frescas notas cítricas. Es un vino amable, con una elegante acidez y final largo y fresco','https://hiperlibertad.vteximg.com.br/arquivos/ids/172292-600-600/VINO-ELEMENTOS-ROSE-750-CC-1-12704.jpg?v=637461714142930000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Chacabuco','Rosado','El Esteco',380,'En nariz presenta aromas de frutas rojas como frutilla y frambuesas en balance con notas cítricas, las cuales generan una sensación muy fresca y potencia los aromas de frutos rojos. En boca es fresco, ágil, con buena acidez y notable persistencia del carácter cítrico frutado','https://hiperlibertad.vteximg.com.br/arquivos/ids/177382-600-600/VINO-CHACABUCO-MBEC-ROSE-750-C-1-11817.jpg?v=637552284618870000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Dilema Rosado X','Rosado','Trapiche',380,'Rosado muy leve, brillante, con tonalidades aceradas y tenues notas salmón. Muy límpido. De aroma delicado y simple, de buena intensidad y frutado. Sabores frescos, frutados y refrescantes. Con un buen balance en boca, agradable entrada dulce y buena acidez. Muy fácil de tomar. Muy rico y elegante final','https://hiperlibertad.vteximg.com.br/arquivos/ids/192368-600-600/VINO-DILEMA-ROSADO-X-750-Ml-1-15589.jpg?v=637802121749870000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Colón Selecto','Rosado','Navarro Correas',450,'De color violáceo intenso. Sabor a frutas negras como moras, casis y notas a eucalipto. Textura suave y final especiado','https://hiperlibertad.vteximg.com.br/arquivos/ids/184708-600-600/VINO-COLON-SELECTO-ROSE-750ML-1-21821.jpg?v=637641621839530000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Tribu Rose','Rosado','El Esteco',600,'Buscamos redimir la variedad Criolla, nativa de nuestro país, y reconoces a los primeros hacedores de vino que hicieron de esta cepa el vino para toda la familia argentina. De piel rosada, le trasfiere al vino un elegante color a cereza brillante. Su aroma de carácter florar y frutal, recuerda a las rosas y frutillas. En boca es fresco, ligero y de acidez equilibrada','https://hiperlibertad.vteximg.com.br/arquivos/ids/189016-600-600/VINO-TRIBU-ROSE-X-750-Ml-1-15185.jpg?v=637757842109030000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Finca Las Moras','Rosado','Finca Las Moras',340,'Rosado intensos con tonos violáceos y leves bordes rubíes - presencia de leves lías finas en suspensión. Aroma: Frutado inicial - vinosos típicos del varietal. Sabor: Entrada frutada - refrescante - seguido de textura mineral o sensación de tiza','https://hiperlibertad.vteximg.com.br/arquivos/ids/177220-600-600/VINO-FINCA-LAS-MOR-ROS-DUL-750-1-16080.jpg?v=637551487220230000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Famiglia Bianchi Rose','Rosado','Bianchi',760,'Posee un color rosa pálido. En nariz, presenta aroma a frutas rojas como cerezas y frambuesas, balanceado con frescas notas cítricas. Es un vino amable, con una elegante acidez y final largo y fresco','https://hiperlibertad.vteximg.com.br/arquivos/ids/167815-600-600/FAMIGLIA-ROS-BLEND-750-CC-1-9441.jpg?v=637322561822130000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Chac Chac','Rosado','Las Perdices',850,'Color: Rosado intensos con tonos violáceos y leves bordes rubíes - presencia de leves lías finas en suspensión. Aroma: Frutado inicial - vinosos típicos del varietal. Sabor: Entrada frutada - refrescante - seguido de textura mineral o sensación de tiza','https://hiperlibertad.vteximg.com.br/arquivos/ids/179349-600-600/VINO-CHAC-CHAC-LP-MAL-ROSE-750ml-1-18532.jpg?v=637568918410400000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('El Coto','Rosado','Rioja',570,'Buscamos redimir la variedad Criolla, nativa de nuestro país, y reconoces a los primeros hacedores de vino que hicieron de esta cepa el vino para toda la familia argentina. De piel rosada, le trasfiere al vino un elegante color a cereza brillante. Su aroma de carácter florar y frutal, recuerda a las rosas y frutillas. En boca es fresco, ligero y de acidez equilibrada','https://www.ibericashop.com/server/Portal_0011957/img/products/el-coto-rosado-50cl_6461663_xxl.jpg' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Mil Rosas','Rosado','Norton',680,'Rosado muy leve, brillante, con tonalidades aceradas y tenues notas salmón. Muy límpido. De aroma delicado y simple, de buena intensidad y frutado. Sabores frescos, frutados y refrescantes. Con un buen balance en boca, agradable entrada dulce y buena acidez. Muy fácil de tomar. Muy rico y elegante final.','https://jumboargentina.vtexassets.com/arquivos/ids/414635/Vino-Rosado-Norton-Mil-Rosas-750-Cc-1-240657.jpg?v=636442103539530000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Aime Rose','Rosado','Ruca Malen',500,'De color violáceo intenso. Sabor a frutas negras como moras, casis y notas a eucalipto. Textura suave y final especiado','https://hiperlibertad.vteximg.com.br/arquivos/ids/177319-600-600/VINO-AIME-ROS-750ML-VINO-AIME-ROS-750ML-1-9267.jpg?v=637551487416600000' ,1);

INSERT INTO products (name,breed,cellar,price,description,image,quantity) VALUES ('Norton Cosecha Tardía Rose','Rosado','Norton',580,'En nariz presenta aromas de frutas rojas como frutilla y frambuesas en balance con notas cítricas, las cuales generan una sensación muy fresca y potencia los aromas de frutos rojos. En boca es fresco, ágil, con buena acidez y notable persistencia del carácter cítrico frutado','https://hiperlibertad.vteximg.com.br/arquivos/ids/177458-600-600/VINO-NORTON-COS-TARD-ROS-750-C-1-18097.jpg?v=637552287976100000' ,1);